AWSTemplateFormatVersion: 2010-09-09
Description: AWS Template for creating simple S3 Bucket.

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: myapp-s3-bucket
      VersioningConfiguration:
        Status: Suspended
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
      - Key: env
        Value: stage

Outputs:
  S3BucketName:
    Description: S3 Bucket Created
    Value: !Ref S3Bucket
    Export:
      Name: myapp-s3-bucket
